export interface Game {
  id: string;
  title: string;
  description: string;
  category: string;
  embedUrl: string;
  gradient: string; // CSS gradient for card thumbnail
  players: string;
  featured?: boolean;
}

export const GAME_CATEGORIES = [
  { id: 'all', label: 'All Games', icon: 'Grid3X3' as const },
  { id: 'action', label: 'Action', icon: 'Swords' as const },
  { id: 'puzzle', label: 'Puzzle', icon: 'Puzzle' as const },
  { id: 'racing', label: 'Racing', icon: 'Gauge' as const },
  { id: 'sports', label: 'Sports', icon: 'Trophy' as const },
  { id: 'arcade', label: 'Arcade', icon: 'Joystick' as const },
  { id: 'strategy', label: 'Strategy', icon: 'Brain' as const },
  { id: 'multiplayer', label: 'Multiplayer', icon: 'Users' as const },
];

// Curated browser-based games using CrazyGames official embed format
export const GAMES: Game[] = [
  // Action
  {
    id: 'stickman-hook',
    title: 'Stickman Hook',
    description: 'Swing from hook to hook to reach the finish line in this addictive physics-based action game.',
    category: 'action',
    embedUrl: 'https://www.crazygames.com/embed/stickman-hook',
    gradient: 'from-rose-600 to-orange-500',
    players: '1 Player',
  },
  {
    id: 'getaway-shootout',
    title: 'Getaway Shootout',
    description: 'Race against your opponent to the escape vehicle. Use wacky physics to gain the upper hand.',
    category: 'action',
    embedUrl: 'https://www.crazygames.com/embed/getaway-shootout',
    gradient: 'from-red-700 to-amber-600',
    players: '2 Players',
  },
  {
    id: 'raft-wars',
    title: 'Raft Wars',
    description: 'Help Simon defend his treasure from pirates, Vikings, and other enemies with your water gun.',
    category: 'action',
    embedUrl: 'https://www.crazygames.com/embed/raft-wars',
    gradient: 'from-sky-600 to-cyan-500',
    players: '1 Player',
  },
  {
    id: 'rooftop-snipers',
    title: 'Rooftop Snipers',
    description: 'Take turns shooting your opponent off the rooftop in this hilarious 2-player sniper duel.',
    category: 'action',
    embedUrl: 'https://www.crazygames.com/embed/rooftop-snipers',
    gradient: 'from-slate-700 to-zinc-500',
    players: '2 Players',
  },
  {
    id: 'smash-karts',
    title: 'Smash Karts',
    description: 'Drive your go-kart, collect power-ups, and smash other players in this explosive multiplayer battle.',
    category: 'action',
    embedUrl: 'https://www.crazygames.com/embed/smash-karts',
    gradient: 'from-fuchsia-600 to-pink-500',
    players: 'Multiplayer',
    featured: true,
  },

  // Puzzle
  {
    id: '2048',
    title: '2048',
    description: 'Slide and merge tiles to reach the legendary 2048 tile in this addictive number puzzle.',
    category: 'puzzle',
    embedUrl: 'https://www.crazygames.com/embed/2048',
    gradient: 'from-amber-600 to-yellow-500',
    players: '1 Player',
  },
  {
    id: 'merge-fruit',
    title: 'Merge Fruit',
    description: 'Drop and merge identical fruits to create bigger ones. How high can you score?',
    category: 'puzzle',
    embedUrl: 'https://www.crazygames.com/embed/merge-fruit',
    gradient: 'from-green-600 to-lime-400',
    players: '1 Player',
  },
  {
    id: 'cut-the-rope',
    title: 'Cut the Rope',
    description: 'Cut the ropes to feed candy to Om Nom. Solve physics puzzles across hundreds of levels.',
    category: 'puzzle',
    embedUrl: 'https://www.crazygames.com/embed/cut-the-rope',
    gradient: 'from-emerald-600 to-teal-400',
    players: '1 Player',
    featured: true,
  },
  {
    id: 'red-ball-4',
    title: 'Red Ball 4',
    description: 'Roll, jump, and bounce through 75 levels of physics-based platforming action.',
    category: 'puzzle',
    embedUrl: 'https://www.crazygames.com/embed/red-ball-4',
    gradient: 'from-red-600 to-rose-400',
    players: '1 Player',
  },
  {
    id: 'bubble-shooter',
    title: 'Bubble Shooter',
    description: 'Match 3 or more bubbles of the same color to pop them. Clear the board to win.',
    category: 'puzzle',
    embedUrl: 'https://www.crazygames.com/embed/bubble-shooter',
    gradient: 'from-blue-500 to-indigo-400',
    players: '1 Player',
  },

  // Racing
  {
    id: 'moto-x3m',
    title: 'Moto X3M',
    description: 'Race your motorcycle through challenging obstacle courses with flips and stunts.',
    category: 'racing',
    embedUrl: 'https://www.crazygames.com/embed/moto-x3m',
    gradient: 'from-orange-600 to-red-500',
    players: '1 Player',
    featured: true,
  },
  {
    id: 'drift-hunters',
    title: 'Drift Hunters',
    description: 'Customize your car and hit the track for some epic drifting action.',
    category: 'racing',
    embedUrl: 'https://www.crazygames.com/embed/drift-hunters',
    gradient: 'from-violet-700 to-purple-500',
    players: '1 Player',
  },
  {
    id: 'parking-fury-3d',
    title: 'Parking Fury 3D',
    description: 'Test your parking skills in a variety of challenging 3D parking situations.',
    category: 'racing',
    embedUrl: 'https://www.crazygames.com/embed/parking-fury-3d',
    gradient: 'from-cyan-700 to-blue-500',
    players: '1 Player',
  },
  {
    id: 'highway-racer-3d',
    title: 'Highway Racer 3D',
    description: 'Race through traffic on the highway at breakneck speed. How far can you go?',
    category: 'racing',
    embedUrl: 'https://www.crazygames.com/embed/highway-racer-3d',
    gradient: 'from-slate-800 to-gray-500',
    players: '1 Player',
  },

  // Sports
  {
    id: 'basketball-stars',
    title: 'Basketball Stars',
    description: 'Compete in fast-paced 2D basketball matches against AI or a friend.',
    category: 'sports',
    embedUrl: 'https://www.crazygames.com/embed/basketball-stars',
    gradient: 'from-orange-700 to-amber-500',
    players: '1-2 Players',
  },
  {
    id: 'football-masters',
    description: 'Choose your team and compete in quick soccer matches with simple one-button controls.',
    title: 'Football Masters',
    category: 'sports',
    embedUrl: 'https://www.crazygames.com/embed/football-masters',
    gradient: 'from-green-700 to-emerald-500',
    players: '1-2 Players',
  },
  {
    id: 'head-soccer-2022',
    title: 'Head Soccer 2022',
    description: 'Play soccer with your head! Score goals using power-ups and special moves.',
    category: 'sports',
    embedUrl: 'https://www.crazygames.com/embed/head-soccer-2022',
    gradient: 'from-sky-700 to-blue-500',
    players: '2 Players',
  },
  {
    id: 'pool-8-ball',
    title: 'Pool 8 Ball',
    description: 'Play classic 8-ball pool against the computer or challenge a friend.',
    category: 'sports',
    embedUrl: 'https://www.crazygames.com/embed/pool-8-ball',
    gradient: 'from-teal-700 to-cyan-500',
    players: '1-2 Players',
  },

  // Arcade
  {
    id: 'crossy-road',
    title: 'Crossy Road',
    description: 'Guide your character across busy roads, rivers, and train tracks without getting hit.',
    category: 'arcade',
    embedUrl: 'https://www.crazygames.com/embed/crossy-road',
    gradient: 'from-lime-600 to-green-500',
    players: '1 Player',
  },
  {
    id: 'temple-run-2',
    title: 'Temple Run 2',
    description: 'Run for your life through ancient temple ruins. Swipe to turn, jump, and slide.',
    category: 'arcade',
    embedUrl: 'https://www.crazygames.com/embed/temple-run-2',
    gradient: 'from-amber-800 to-yellow-600',
    players: '1 Player',
    featured: true,
  },
  {
    id: 'geometry-dash',
    title: 'Geometry Dash',
    description: 'Jump and fly through danger in this rhythm-based action platformer.',
    category: 'arcade',
    embedUrl: 'https://www.crazygames.com/embed/geometry-dash',
    gradient: 'from-fuchsia-700 to-violet-500',
    players: '1 Player',
  },
  {
    id: 'flappy-bird',
    title: 'Flappy Bird',
    description: 'Tap to flap your wings and navigate through the pipes. Simple but incredibly addictive.',
    category: 'arcade',
    embedUrl: 'https://www.crazygames.com/embed/flappy-bird',
    gradient: 'from-sky-500 to-green-400',
    players: '1 Player',
  },

  // Strategy
  {
    id: 'bloons-td',
    title: 'Bloons TD',
    description: 'Place monkey towers to pop waves of colorful balloons before they escape.',
    category: 'strategy',
    embedUrl: 'https://www.crazygames.com/embed/bloons-td',
    gradient: 'from-rose-500 to-pink-400',
    players: '1 Player',
  },
  {
    id: 'age-of-war',
    title: 'Age of War',
    description: 'Evolve through the ages and destroy the enemy base. Build units and turrets to defend.',
    category: 'strategy',
    embedUrl: 'https://www.crazygames.com/embed/age-of-war',
    gradient: 'from-stone-700 to-amber-600',
    players: '1 Player',
  },
  {
    id: 'kingdom-rush',
    title: 'Kingdom Rush',
    description: 'Defend your kingdom by building towers, summoning heroes, and using powerful spells.',
    category: 'strategy',
    embedUrl: 'https://www.crazygames.com/embed/kingdom-rush',
    gradient: 'from-yellow-700 to-orange-500',
    players: '1 Player',
  },
  {
    id: 'tower-defense',
    title: 'Tower Defense',
    description: 'Strategically place towers to defend your base from endless waves of enemies.',
    category: 'strategy',
    embedUrl: 'https://www.crazygames.com/embed/tower-defense',
    gradient: 'from-indigo-700 to-blue-500',
    players: '1 Player',
  },

  // Multiplayer
  {
    id: 'slitherio',
    title: 'Slither.io',
    description: 'Grow your snake by consuming glowing orbs. Outmaneuver other players to become the biggest.',
    category: 'multiplayer',
    embedUrl: 'https://www.crazygames.com/embed/slitherio',
    gradient: 'from-emerald-600 to-green-400',
    players: 'Multiplayer',
    featured: true,
  },
  {
    id: 'paperio-2',
    title: 'Paper.io 2',
    description: 'Capture territory by drawing loops. Don\'t let other players cross your trail.',
    category: 'multiplayer',
    embedUrl: 'https://www.crazygames.com/embed/paperio-2',
    gradient: 'from-sky-600 to-indigo-400',
    players: 'Multiplayer',
  },
  {
    id: 'agario',
    title: 'Agar.io',
    description: 'Consume smaller cells to grow. Avoid bigger players or get consumed yourself.',
    category: 'multiplayer',
    embedUrl: 'https://www.crazygames.com/embed/agario',
    gradient: 'from-pink-600 to-rose-400',
    players: 'Multiplayer',
  },
  {
    id: 'krunker',
    title: 'Krunker',
    description: 'Fast-paced multiplayer FPS with pixelated graphics. Compete in various game modes.',
    category: 'multiplayer',
    embedUrl: 'https://www.crazygames.com/embed/krunker',
    gradient: 'from-zinc-700 to-neutral-500',
    players: 'Multiplayer',
  },
];
