import fs from 'fs';
import path from 'path';

const ICON_MAP = {
  Search: 'RiSearchLine', SearchX: 'RiSearchLine', Film: 'RiMovie2Line', Tv: 'RiTvLine',
  Home: 'RiHome5Line', Radio: 'RiBroadcastLine', Gamepad2: 'RiGamepadLine',
  Download: 'RiDownloadLine', X: 'RiCloseLine', LogIn: 'RiLoginBoxLine',
  LogOut: 'RiLogoutBoxLine', Globe: 'RiGlobeLine', Clapperboard: 'RiMovieLine',
  BookOpen: 'RiBookOpenLine', Users: 'RiGroupLine', Flame: 'RiFireLine',
  ShieldOff: 'RiShieldLine', Shield: 'RiShieldCheckLine', ShieldAlert: 'RiAlertLine',
  ShieldCheck: 'RiShieldCheckLine', User: 'RiUserLine', UserPlus: 'RiUserAddLine',
  MoreHorizontal: 'RiMore2Line', Play: 'RiPlayFill', PlayCircle: 'RiPlayCircleLine',
  Heart: 'RiHeartLine', Star: 'RiStarLine', ChevronLeft: 'RiArrowLeftSLine',
  ChevronRight: 'RiArrowRightSLine', ChevronDown: 'RiArrowDownSLine',
  ChevronUp: 'RiArrowUpSLine', ChevronFirst: 'RiSkipBackMiniLine',
  ChevronLast: 'RiSkipForwardMiniLine', ArrowLeft: 'RiArrowLeftLine',
  ArrowRight: 'RiArrowRightLine', Info: 'RiInformationLine', Clock: 'RiTimeLine',
  TrendingUp: 'RiTrendingUpLine', Eye: 'RiEyeLine', EyeOff: 'RiEyeOffLine',
  ThumbsUp: 'RiThumbUpLine', Share2: 'RiShareLine', ExternalLink: 'RiExternalLinkLine',
  Volume2: 'RiVolumeUpLine', VolumeX: 'RiVolumeMuteLine', Maximize: 'RiFullscreenLine',
  Settings: 'RiSettings3Line', Lock: 'RiLockLine', Mail: 'RiMailLine',
  Key: 'RiKeyLine', Loader2: 'RiLoader4Line', AlertTriangle: 'RiAlertLine',
  AlertCircle: 'RiErrorWarningLine', Check: 'RiCheckLine', XCircle: 'RiCloseCircleLine',
  CheckCircle: 'RiCheckboxCircleLine', CheckCircle2: 'RiCheckboxCircleLine',
  RefreshCw: 'RiRefreshLine', Copy: 'RiFileCopyLine', Menu: 'RiMenuLine',
  Sparkles: 'RiSparklingLine', Zap: 'RiFlashlightLine', Bookmark: 'RiBookmarkLine',
  Calendar: 'RiCalendarLine', Filter: 'RiFilterLine', Grid: 'RiLayoutGridLine',
  List: 'RiListUnordered', Music: 'RiMusicLine', Mic: 'RiMicLine',
  MapPin: 'RiMapPinLine', Phone: 'RiPhoneLine', Camera: 'RiCameraLine',
  Image: 'RiImageLine', FileText: 'RiFileTextLine', Link: 'RiLinkLine',
  Code: 'RiCodeLine', Trash2: 'RiDeleteBinLine', Edit: 'RiEditLine',
  Plus: 'RiAddLine', Minus: 'RiSubtractLine', HelpCircle: 'RiQuestionLine',
  Send: 'RiSendPlaneLine', MessageCircle: 'RiChat1Line', Bell: 'RiNotificationLine',
  Palette: 'RiPaletteLine', Monitor: 'RiMonitorLine', Smartphone: 'RiSmartphoneLine',
  Wifi: 'RiWifiLine', WifiOff: 'RiWifiOffLine', SkipBack: 'RiSkipBackLine',
  SkipForward: 'RiSkipForwardLine', Pause: 'RiPauseFill', Subtitles: 'RiSubtitlesLine',
  Flag: 'RiFlagLine', Tag: 'RiPriceTag3Line', DollarSign: 'RiMoneyDollarCircleLine',
  Award: 'RiAwardLine', Crown: 'RiVipCrownLine', Target: 'RiFocusLine',
  Timer: 'RiTimerLine', Layers: 'RiStackLine', Layout: 'RiLayoutLine',
  Compass: 'RiCompassLine', Cloud: 'RiCloudLine', Sun: 'RiSunLine',
  Moon: 'RiMoonLine', CircleDot: 'RiRecordCircleLine', Circle: 'RiCheckboxBlankCircleLine',
  RotateCcw: 'RiRestartLine', PictureInPicture2: 'RiPictureInPicture2Line',
  SortAsc: 'RiSortAsc', Chevron: 'RiArrowDownSLine', Hash: 'RiHashLine',
  PanelLeftClose: 'RiSideBarLine', PanelLeft: 'RiSideBarLine', ScanLine: 'RiScanLine',
  MonitorPlay: 'RiMonitorLine', Tv2: 'RiTvLine', BadgeCheck: 'RiCheckboxCircleFill',
  Crosshair: 'RiFocus3Line', TimerReset: 'RiRestartLine', Volume1: 'RiVolumeUpLine',
  Captions: 'RiSubtitlesLine', CaptionsOff: 'RiSubtitlesLine',
  TriangleAlert: 'RiAlertLine', InfoIcon: 'RiInformationLine',
  CircleCheck: 'RiCheckboxCircleLine', FormInput: 'RiEditLine',
  ArrowLeftRight: 'RiArrowLeftRightLine', GripVertical: 'RiDraggable',
  Upload: 'RiUploadLine', PlaySquare: 'RiPlayCircleLine', ListVideo: 'RiVideoLine',
  RectangleHorizontal: 'RiLayoutLine', MonitorUp: 'RiMonitorLine',
  ArrowUp: 'RiArrowUpLine', ArrowDown: 'RiArrowDownLine',
  EllipsisVertical: 'RiMore2Line', Ellipsis: 'RiMore2Line',
  MenuSquare: 'RiLayoutGridLine', LayoutGrid: 'RiLayoutGridLine',
  LayoutList: 'RiListUnordered', GalleryHorizontal: 'RiGalleryLine',
  GalleryVertical: 'RiGalleryLine', GalleryHorizontalEnd: 'RiGalleryLine',
  MoveRight: 'RiArrowRightLine', MoveLeft: 'RiArrowLeftLine',
  Ratio: 'RiAspectRatioLine', Pipette: 'RiPaletteLine',
  ToggleRight: 'RiToggleLine', ToggleLeft: 'RiToggleLine',
  Signal: 'RiSignalWifiLine', CircleUser: 'RiUserLine',
  CircleUserRound: 'RiUserLine', UserRound: 'RiUserLine',
  UserRoundPlus: 'RiUserAddLine', LockKeyhole: 'RiLockLine',
  LockOpen: 'RiLockUnlockLine', Unplug: 'RiUnplugLine',
  Keyboard: 'RiKeyboardLine', Mouse: 'RiCursorLine',
  Command: 'RiTerminalBoxLine', Terminal: 'RiTerminalBoxLine',
  FileVideo: 'RiVideoLine', FileAudio: 'RiMusicLine', FileImage: 'RiImageLine',
  Folder: 'RiFolderLine', FolderOpen: 'RiFolderOpenLine',
  Archive: 'RiArchiveLine', Package: 'RiPackageLine', Gift: 'RiGiftLine',
  StarOff: 'RiStarLine', StarHalf: 'RiStarHalfLine', HeartOff: 'RiHeartLine',
  BookmarkPlus: 'RiBookmarkLine', BookmarkMinus: 'RiBookmarkLine',
  BookmarkCheck: 'RiBookmarkFill', ThumbsDown: 'RiThumbDownLine',
  Share: 'RiShareLine', MessageSquare: 'RiChat1Line',
  SendHorizontal: 'RiSendPlaneLine', Megaphone: 'RiAnnounceLine',
  Newspaper: 'RiNewspaperLine', Globe2: 'RiGlobeLine', Languages: 'RiTranslate2',
  CreditCard: 'RiBankCardLine', Wallet: 'RiWalletLine', Receipt: 'RiBillLine',
  Clock3: 'RiTimeLine', Clock4: 'RiTimerLine', History: 'RiHistoryLine',
  CalendarDays: 'RiCalendarLine', CalendarCheck: 'RiCalendarCheckLine',
  CalendarRange: 'RiCalendar2Line', TimerOff: 'RiTimerLine',
  Hourglass: 'RiTimerLine', SunMedium: 'RiSunLine', Sunset: 'RiSunLine',
  Sunrise: 'RiSunLine', CloudRain: 'RiCloudyLine', CloudSnow: 'RiCloudyLine',
  CloudFog: 'RiMistLine', CloudLightning: 'RiFlashlightLine',
  CloudOff: 'RiCloudOffLine', CloudSun: 'RiCloudLine',
  CloudMoon: 'RiMoonCloudyLine', Wind: 'RiWindyLine',
  Thermometer: 'RiTempHotLine', Umbrella: 'RiRainyLine', Map: 'RiMapLine',
  MapPinned: 'RiMapPinLine', Navigation: 'RiCompassLine',
  Mountain: 'RiMountainLine', TreePine: 'RiPlantLine', Flower: 'RiPlantLine',
  Leaf: 'RiLeafLine', Bug: 'RiBugLine', Fish: 'RiFishLine',
  Dog: 'RiBearSmileLine', Cat: 'RiBearSmileLine', Bird: 'RiTwitterXLine',
  Feather: 'RiQuillPenLine', Footprints: 'RiFootprintLine',
  Fingerprint: 'RiFingerprintLine', ScanFace: 'RiUserScanLine',
  Scan: 'RiScanLine', ScanBarcode: 'RiBarcodeLine', QrCode: 'RiQrCodeLine',
  AppWindow: 'RiWindowLine', Browser: 'RiGlobalLine', Server: 'RiServerLine',
  Database: 'RiDatabase2Line', HardDrive: 'RiHardDriveLine', Cpu: 'RiCpuLine',
  MemoryStick: 'RiRamLine', Wifi0: 'RiWifiLine', Bluetooth: 'RiBluetoothLine',
  BluetoothOff: 'RiBluetoothOffLine', Usb: 'RiUsbLine', Battery: 'RiBatteryLine',
  BatteryCharging: 'RiBatteryChargeLine', BatteryFull: 'RiBatteryFill',
  BatteryLow: 'RiBatteryLowLine', BatteryMedium: 'RiBattery2ChargeLine',
  BatteryWarning: 'RiBatteryWarningLine', Plug: 'RiPlugLine',
  PlugZap: 'RiPlugLine', Power: 'RiPowerOffLine', PowerOff: 'RiPowerOffLine',
  Restart: 'RiRestartLine', Sleep: 'RiMoonLine', ScreenShare: 'RiComputerLine',
  MonitorX: 'RiComputerLine', MonitorOff: 'RiComputerLine', Display: 'RiComputerLine',
  Projector: 'RiProjectorLine', TvOff: 'RiTvLine', Speaker: 'RiSpeakerLine',
  VolumeOff: 'RiVolumeMuteLine', Headphones: 'RiHeadphoneLine', Ear: 'RiEarLine',
  AudioLines: 'RiEqualizerLine', RadioReceiver: 'RiBroadcastLine',
  Music2: 'RiMusic2Line', Music3: 'RiMusicLine', Music4: 'RiMusicLine',
  Disc: 'RiDiscLine', Vinyl: 'RiDiscLine', Mic2: 'RiMicLine',
  MicOff: 'RiMicOffLine', Video: 'RiVideoLine', VideoOff: 'RiVideoLine',
  CameraOff: 'RiCameraOffLine', CameraSwitch: 'RiCameraSwitchLine',
  Webcam: 'RiWebcamLine', ImageOff: 'RiImageLine',
  ImagePlus: 'RiImageAddLine', ImageMinus: 'RiImageLine', Images: 'RiGalleryLine',
  Frame: 'RiFrameLine', Crop: 'RiCropLine', FlipHorizontal: 'RiFlipHorizontalLine',
  FlipVertical: 'RiFlipVerticalLine', RotateCw: 'RiRefreshLine',
  ZoomIn: 'RiZoomInLine', ZoomOut: 'RiZoomOutLine', Maximize2: 'RiFullscreenLine',
  Minimize: 'RiFullscreenExitLine', Expand: 'RiExpandDiagonalLine',
  Shrink: 'RiContractLeftRightLine', Move: 'RiDragMoveLine',
  MoveDiagonal: 'RiDragMove2Line', MoveHorizontal: 'RiDragMoveLine',
  MoveVertical: 'RiDragMoveLine', Split: 'RiSplitCellsHorizontal',
  Columns: 'RiLayoutColumnLine', Rows: 'RiLayoutRowLine',
  PanelTop: 'RiLayoutTopLine', PanelBottom: 'RiLayoutBottomLine',
  PanelTopClose: 'RiLayoutTopLine', PanelBottomClose: 'RiLayoutBottomLine',
  PanelRightClose: 'RiLayoutRightLine', PanelRight: 'RiLayoutRightLine',
  Sidebar: 'RiSideBarLine', SidebarOpen: 'RiSideBarLine', SidebarClose: 'RiSideBarLine',
  Sheet: 'RiFileLine', Table: 'RiTableLine', Table2: 'RiTable2Line',
  Kanban: 'RiKanbanLine', GanttChart: 'RiBarChartLine', CalendarRange2: 'RiCalendar2Line',
  StickyNote: 'RiStickyNoteLine', Notebook: 'RiBookLine', NotebookPen: 'RiPencilLine',
  Pen: 'RiPencilLine', PenLine: 'RiPencilLine', PenTool: 'RiPencilRulerLine',
  Pencil: 'RiPencilLine', Highlighter: 'RiHighlighterLine',
  Marker: 'RiMarkerPenLine', PaintBucket: 'RiPaintBrushLine',
  Paintbrush: 'RiPaintBrushLine', Brush: 'RiPaintBrushLine', Eraser: 'RiEraserLine',
  Type: 'RiText', Heading: 'RiHeading', Heading1: 'RiH1', Heading2: 'RiH2',
  Heading3: 'RiH3', Heading4: 'RiH4', Heading5: 'RiH5', Heading6: 'RiH6',
  Bold: 'RiBold', Italic: 'RiItalic', Underline: 'RiUnderline',
  Strikethrough: 'RiStrikethrough', AlignLeft: 'RiAlignLeft',
  AlignCenter: 'RiAlignCenter', AlignRight: 'RiAlignRight',
  AlignJustify: 'RiAlignJustify', Indent: 'RiIndentIncrease',
  Outdent: 'RiIndentDecrease', WrapText: 'RiTextWrap',
  RemoveFormatting: 'RiFormatClear', Superscript: 'RiSuperscript',
  Subscript: 'RiSubscript', Quote: 'RiDoubleQuotesL', Code2: 'RiCodeLine',
  Braces: 'RiCodeBoxLine', Pilcrow: 'RiParagraph', ListOrdered: 'RiListOrdered',
  ListChecks: 'RiListCheck', ListFilter: 'RiFilterLine', ListMusic: 'RiMusic2Line',
  ListPlus: 'RiAddLine', ListMinus: 'RiSubtractLine', ListX: 'RiCloseLine',
  Square: 'RiCheckboxBlankLine', SquareCheck: 'RiCheckboxLine',
  SquareCheckBig: 'RiCheckboxFill', SquareDot: 'RiCheckboxBlankFill',
  SquareMinus: 'RiIndeterminateCircleLine', SquarePlus: 'RiAddCircleLine',
  SquareSlash: 'RiForbidLine', CircleSlash: 'RiForbidLine',
  Octagon: 'RiStopLine', OctagonX: 'RiStopLine', Hexagon: 'RiHexagonLine',
  Pentagon: 'RiPentagonLine', Diamond: 'RiDiamondLine', Triangle: 'RiTriangleLine',
  Cross: 'RiCloseLine', PlusCircle: 'RiAddCircleLine',
  MinusCircle: 'RiSubtractLine', XCircle2: 'RiCloseCircleLine',
  AlertOctagon: 'RiErrorWarningLine', Ban: 'RiForbidLine', Unlink: 'RiLinkUnlink',
  Unlink2: 'RiLinkUnlink', Link2: 'RiLinkLine', Link2Off: 'RiLinkUnlink',
  Paperclip: 'RiAttachmentLine', Paperclip2: 'RiAttachment2Line',
  Pin: 'RiPushpinLine', PinOff: 'RiPushpinLine', Magnet: 'RiMagnetLine',
  Waypoints: 'RiMapPinLine', Locate: 'RiMapPinLine', LocateFixed: 'RiMapPinLine',
  MoveUp: 'RiArrowUpLine', MoveDown: 'RiArrowDownLine',
  ArrowUpDown: 'RiArrowUpDownLine', ArrowUpLeft: 'RiArrowUpLeftLine',
  ArrowUpRight: 'RiArrowUpRightLine', ArrowDownLeft: 'RiArrowDownLeftLine',
  ArrowDownRight: 'RiArrowDownRightLine', ArrowUpFromLine: 'RiArrowUpLine',
  ArrowDownToLine: 'RiArrowDownLine', ArrowUpToLine: 'RiArrowUpLine',
  CornerDownLeft: 'RiArrowDownLeftLine', CornerDownRight: 'RiArrowDownRightLine',
  CornerUpLeft: 'RiArrowUpLeftLine', CornerUpRight: 'RiArrowUpRightLine',
  ChevronsLeft: 'RiArrowLeftDoubleLine', ChevronsRight: 'RiArrowRightDoubleLine',
  ChevronsUpDown: 'RiArrowUpDownLine', ChevronsLeftRight: 'RiArrowLeftRightLine',
  CircleDotDashed: 'RiRecordCircleLine', Dot: 'RiRecordCircleLine',
  DotsHorizontal: 'RiMoreLine', DotsVertical: 'RiMore2Line', Grip: 'RiDraggable',
  GripHorizontal: 'RiDraggable', Dice1: 'RiDiceLine', Dice2: 'RiDiceLine',
  Dice3: 'RiDiceLine', Dice4: 'RiDiceLine', Dice5: 'RiDiceLine', Dice6: 'RiDiceLine',
  Trophy: 'RiTrophyLine', Medal: 'RiMedalLine', Swords: 'RiSwordLine',
  ShieldHalf: 'RiShieldLine', ShieldMinus: 'RiShieldLine',
  ShieldPlus: 'RiShieldLine', ShieldQuestion: 'RiShieldLine', ShieldX: 'RiShieldLine',
  Scale: 'RiScalesLine', Gavel: 'RiGavelLine', Landmark: 'RiGovernmentLine',
  Building: 'RiBuildingLine', Building2: 'RiBuilding2Line', Store: 'RiStoreLine',
  Warehouse: 'RiHomeLine', Castle: 'RiBuildingLine', Tent: 'RiTentLine',
  Car: 'RiCarLine', CarFront: 'RiCarLine', Bus: 'RiBusLine',
  Truck: 'RiTruckLine', Bike: 'RiEBikeLine', Ship: 'RiShipLine',
  Plane: 'RiPlaneLine', Rocket: 'RiRocketLine', PlaneTakeoff: 'RiPlaneLine',
  PlaneLanding: 'RiPlaneLine', TrainFront: 'RiTrainLine',
  TrainTrack: 'RiTrainLine', FootprintsIcon: 'RiFootprintLine',
  Accessibility: 'RiAccessibleLine', Baby: 'RiBabyLine',
  UsersRound: 'RiGroupLine', UserCheck: 'RiUserLine', UserX: 'RiUserLine',
  UserMinus: 'RiUserLine', UserCog: 'RiUserSettingsLine',
  Users2: 'RiTeamLine', PersonStanding: 'RiUserLine', Hand: 'RiHandCoinLine',
  HandMetal: 'RiHandCoinLine', ClapperboardOpen: 'RiMovieLine',
  FilmIcon: 'RiMovie2Line', Reel: 'RiFilmLine', ClapperboardClose: 'RiMovieLine',
  Popcorn: 'RiMovie2Line', Ticket: 'RiTicketLine', PartyPopper: 'RiFlagLine',
  Confetti: 'RiFlagLine', SparklesIcon: 'RiSparklingLine', Wand: 'RiMagicLine',
  WandSparkles: 'RiMagicLine', GraduationCap: 'RiGraduationCapLine',
  School: 'RiSchoolLine', BookMarked: 'RiBookmarkFill',
  BookOpenCheck: 'RiBookOpenLine', Library: 'RiBook2Line',
  BookCopy: 'RiFileCopyLine', BookX: 'RiBookLine', BookType: 'RiBookLine',
  BookText: 'RiBook2Line', BookHeart: 'RiBookHeartLine',
  ScrollText: 'RiScrollToBottomLine', File: 'RiFileLine',
  FilePlus: 'RiFileAddLine', FileMinus: 'RiFileLine',
  FileCheck: 'RiFileCheckLine', FileX: 'RiFileCloseLine',
  FileLock: 'RiFileLockLine', FileLock2: 'RiFileLockLine',
  FileUnlock: 'RiFileUnlockLine', FileWarning: 'RiFileWarningLine',
  FileQuestion: 'RiFileQuestionLine', FileSearch: 'RiFileSearchLine',
  FileMinus2: 'RiFileReduceLine', FilePlus2: 'RiFileAddLine',
  FileCode: 'RiFileCodeLine', FileJson: 'RiFileCodeLine',
  FileSpreadsheet: 'RiFileExcel2Line', FilePen: 'RiFileEditLine',
  FilePencil: 'RiFileEditLine', FileSignature: 'RiFileEditLine',
  FileCog: 'RiFileSettingsLine', FileHeart: 'RiFileHeartLine',
  FileMusic: 'RiFileMusicLine', FileVideo2: 'RiFileVideoLine',
  FileImage2: 'RiFileImageLine', FileArchive: 'RiFileArchiveLine',
  FileOutput: 'RiFileChartLine', FileInput: 'RiFileUploadLine',
  FileDown: 'RiFileDownloadLine', FileUp: 'RiFileUploadLine',
  FolderPlus: 'RiFolderAddLine', FolderMinus: 'RiFolderReduceLine',
  FolderX: 'RiFolderCloseLine', FolderLock: 'RiFolderLockLine',
  FolderSearch: 'RiFolderSearchLine', FolderHeart: 'RiFolderHeartLine',
  FolderOpenDot: 'RiFolderOpenLine', FolderSync: 'RiFolderTransferLine',
  PackagePlus: 'RiPackageLine', PackageMinus: 'RiPackageLine',
  PackageX: 'RiPackageLine', PackageCheck: 'RiPackageLine',
  PackageOpen: 'RiPackageLine', PackageSearch: 'RiPackageLine',
  Box: 'RiBoxLine', Boxes: 'RiBox3Line', ArchiveRestore: 'RiArchiveLine',
  ArchiveX: 'RiArchiveLine', Inbox: 'RiInboxLine', InboxIcon: 'RiInboxLine',
  MailPlus: 'RiMailAddLine', MailMinus: 'RiMailLine', MailX: 'RiMailCloseLine',
  MailCheck: 'RiMailCheckLine', MailOpen: 'RiMailOpenLine',
  MailQuestion: 'RiMailQuestionLine', MailWarning: 'RiMailWarningLine',
  MailSearch: 'RiMailSearchLine', MailLock: 'RiMailLockLine',
  AtSign: 'RiAtLine', PhoneCall: 'RiPhoneLine', PhoneForwarded: 'RiPhoneLine',
  PhoneIncoming: 'RiPhoneLine', PhoneMissed: 'RiPhoneLine',
  PhoneOff: 'RiPhoneLine', PhoneOutgoing: 'RiPhoneLine',
  Voicemail: 'RiVoicemailLine', Forward: 'RiForwardLine', Reply: 'RiReplyLine',
  ReplyAll: 'RiReplyAllLine', Settings2: 'RiSettings3Line',
  SettingsX: 'RiSettings3Line', SlidersHorizontal: 'RiEqualizerLine',
  SlidersVertical: 'RiEqualizerLine', ToggleLeft: 'RiToggleLine',
  ToggleRight2: 'RiToggleLine', SwitchCamera: 'RiCameraSwitchLine',
  Switch: 'RiToggleLine', Button: 'RiCheckboxLine', MousePointer: 'RiCursorLine',
  MousePointerClick: 'RiCursorLine', Pointer: 'RiCursorLine',
  HandClick: 'RiCursorLine', PointerIcon: 'RiCursorLine',
  TextCursor: 'RiCursorLine', TextCursorInput: 'RiCursorLine',
  MoveIcon: 'RiDragMoveLine', WholeWord: 'RiText', CaseSensitive: 'RiText',
  Regex: 'RiCodeLine', Replace: 'RiFindReplaceLine',
  ReplaceAll: 'RiFindReplaceLine', SearchCode: 'RiSearchLine',
  SearchCheck: 'RiSearchLine', FilterX: 'RiFilterLine',
  SortAscending: 'RiSortAsc', SortDescending: 'RiSortDesc',
  ArrowUpDownIcon: 'RiArrowUpDownLine', ArrowNarrowDown: 'RiArrowDownSLine',
  ArrowNarrowUp: 'RiArrowUpSLine', ArrowNarrowLeft: 'RiArrowLeftSLine',
  ArrowNarrowRight: 'RiArrowRightSLine', SlightlySmiling: 'RiEmotionLine',
  Frown: 'RiEmotionUnhappyLine', Meh: 'RiEmotionNormalLine',
  Sparkle: 'RiSparklingLine', Airplay: 'RiCastLine', Chromecast: 'RiCastLine',
  Cast: 'RiCastLine', Pip: 'RiPictureInPicture2Line', CaptionsIcon: 'RiSubtitlesLine',
  AudioDescription: 'RiSubtitlesLine', Voice: 'RiVoiceprintLine',
  AccessibilityIcon: 'RiAccessibleLine', Signed: 'RiSignLanguageLine',
};

const files = process.argv.slice(2);
let totalChanges = 0;

for (const filePath of files) {
  let content = fs.readFileSync(filePath, 'utf-8');
  const lucideImportMatch = content.match(/import\s*\{([^}]+)\}\s*from\s*['"]lucide-react['"]/);
  if (!lucideImportMatch) continue;
  
  const importBlock = lucideImportMatch[1];
  const icons = importBlock.split(',').map(s => s.trim()).filter(Boolean);
  
  const remixImports = new Set();
  let newContent = content;
  const mappedIcons = [];
  
  for (const icon of icons) {
    const remixIcon = ICON_MAP[icon];
    if (!remixIcon) {
      console.log(`  WARNING: No mapping for ${icon} in ${path.basename(filePath)}`);
      continue;
    }
    remixImports.add(remixIcon);
    mappedIcons.push({ from: icon, to: remixIcon });
  }
  
  // Replace JSX usage and references - sort by length descending to avoid partial replacements
  for (const { from, to } of mappedIcons.sort((a, b) => b.from.length - a.from.length)) {
    // Replace as JSX: <Search className= -> <RiSearchLine className=
    newContent = newContent.replace(new RegExp(`<${from}(\\s|>|\\.)`, 'g'), `<${to}$1`);
    // Replace as component ref: icon: Search -> icon: RiSearchLine
    newContent = newContent.replace(new RegExp(`(?<![A-Za-z0-9])${from}(?![A-Za-z0-9])`, 'g'), to);
  }
  
  // Replace the import line
  const importArr = Array.from(remixImports).sort();
  if (importArr.length === 0) {
    // Remove the empty import line
    newContent = newContent.replace(/import\s*\{[^}]*\}\s*from\s*['"]lucide-react['"]\s*;?\n?/, '');
  } else {
    const newImport = `import { ${importArr.join(', ')} } from '@remixicon/react';`;
    newContent = newContent.replace(/import\s*\{[^}]+\}\s*from\s*['"]lucide-react['"]\s*;?\n?/, newImport + '\n');
  }
  
  fs.writeFileSync(filePath, newContent, 'utf-8');
  console.log(`  Migrated: ${path.basename(filePath)} (${mappedIcons.length} icons)`);
  totalChanges += mappedIcons.length;
}

console.log(`\nTotal: ${totalChanges} icon migrations`);
